### ISSUE TITLE
Usage of feature_set()

### ISSUE THREAD

**Issue by mitchelloharawild** [robjhyndman/feasts-talk#2]
https://github.com/robjhyndman/feasts-talk/blob/8a93e16b600fec335653e05b5dbf260c7b9c0cfd/feasts.Rmd#L281-L295

It would be better to say "Features based on all features from the feasts package". Currently `feature_set(pkgs = "feasts")` only gives those as they are my test/prototype group. Soon all features will be registered and accessible using `feature_set()`.

**Comment by robjhyndman** [comment]
Fixed in https://github.com/robjhyndman/feasts-talk/commit/42d6e17243d4afb3fce25fab63a9da518d9e57fd
